### ISSUE TITLE
Change icon color in incognito mode

### ISSUE THREAD

**Issue by Stanzilla** [EdmundLeex/github-notification#4]
Currently when in in-cognito mode or when using a dark theme, the icon is still black on a dark background, chrome extensions support tints (https://developer.chrome.com/extensions/themes#tints) so that would be a nice workaround

**Comment by EdmundLeex** [comment]
@Stanzilla I don't recommend using in incognito mode personally as it does contain your key once you config it. But by all means, PR is welcome :D
